name: EC2 Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Prepare remote folder
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2.pem \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "sudo mkdir -p /var/www/test_project && sudo chown -R ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} /var/www/test_project"

      - name: Deploy code to EC2
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2.pem" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/test_project/